# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c9220dc657857c6ec16e56a9edf470812b2963aaf5482753793e42aae124ed17f2739f51f9230dade56f4847aa16dffd32f0eb147efd5a51604a71bf39a56e3

test:
  secret_key_base: 38b49154fa7084a0aa9348d18b9df207f7d4900a32f9af29f62a26396ddef7757921c2dacb322df354381cc794dd1882a48844e37362a8a38a20eac0db9a7432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
